import { ROOT_KEYS } from "./root.js";
export const GENERAL_ROOM_KEYS = {
    CREATED_AT: "createdAt",
    RULES: "rules",
    MATCH_POINT: "matchPoint",
    THINKING_TIME_IN_SEC: "thinkingTimeInSec",
    STATE: "state",
    HOST: "host",
    GUEST: "guest",
    UID: "uid",
    NAME: "name",
    SCORE: "score",
    MANA: "mana",
    HAS_FINISHED_INTERLUDE: "hasFinishedInterlude",
    FINAL_WINNER_OF_MATCH: "finalWinnerOfMatch",
    GAME: "game",
    PHASE: "phase",
    HAND_SUBMISSION_DEADLINE: "handSubmissionDeadline",
    RECONNECT_DEADLINE: "reconnectDeadline",
    SUBMITTED_PLAYERS: "submittedPlayers",
    ROUND_NUMBER: "roundNumber",
    HANDS_OF: "handsOf",
    RESOLVED_ROUND: "resolvedRound",
    MANA_GAIN: "manaGain",
    SCORE_GAIN: "scoreGain",
    SELECTED_HAND: "selectedHand",
    WINNER_OF_ROUND: "winnerOfRound",
    RESOLVED_AT: "resolvedAt",
    NEXT_PHASE_AT: "nextPhaseAt",
};
export const PRIVATE_ROOM_KEYS = {
    SPECTATORS: "spectators",
    JOIN_CODE_HASH: "joinCodeHash",
    READY: "ready",
    BACK_TO_LOBBY_AT: "backToLobbyAt",
};
export const PRIVATE_ROOM_JOIN_CODE_KEYS = {
    ROOM_ID: "roomId",
    CREATED_AT: "createdAt",
};
export const DATABASE_PATHS_FOR_ROOMS = {
    privateRoomsRoot: () => ROOT_KEYS.PRIVATE_ROOMS,
    privateRoom: (roomId) => `${ROOT_KEYS.PRIVATE_ROOMS}/${roomId}`,
    privateRoomState: (roomId) => `${ROOT_KEYS.PRIVATE_ROOMS}/${roomId}/${GENERAL_ROOM_KEYS.STATE}`,
    privateRoomGuestName: (roomId) => `${ROOT_KEYS.PRIVATE_ROOMS}/${roomId}/${GENERAL_ROOM_KEYS.GUEST}/${GENERAL_ROOM_KEYS.NAME}`,
    guestScore: (roomId, isPrivateMatch = false) => `${isPrivateMatch ? ROOT_KEYS.PRIVATE_ROOMS : ROOT_KEYS.RANDOM_ROOMS}/${roomId}/${GENERAL_ROOM_KEYS.GUEST}/${GENERAL_ROOM_KEYS.SCORE}`,
    guestMana: (roomId, isPrivateMatch = false) => `${isPrivateMatch ? ROOT_KEYS.PRIVATE_ROOMS : ROOT_KEYS.RANDOM_ROOMS}/${roomId}/${GENERAL_ROOM_KEYS.GUEST}/${GENERAL_ROOM_KEYS.MANA}`,
    hostScore: (roomId, isPrivateMatch = false) => `${isPrivateMatch ? ROOT_KEYS.PRIVATE_ROOMS : ROOT_KEYS.RANDOM_ROOMS}/${roomId}/${GENERAL_ROOM_KEYS.HOST}/${GENERAL_ROOM_KEYS.SCORE}`,
    hostMana: (roomId, isPrivateMatch = false) => `${isPrivateMatch ? ROOT_KEYS.PRIVATE_ROOMS : ROOT_KEYS.RANDOM_ROOMS}/${roomId}/${GENERAL_ROOM_KEYS.HOST}/${GENERAL_ROOM_KEYS.MANA}`,
    privateRoomSpectator: (roomId) => `${ROOT_KEYS.PRIVATE_ROOMS}/${roomId}/${PRIVATE_ROOM_KEYS.SPECTATORS}`,
    game: (roomId, isPrivateMatch = false) => `${isPrivateMatch ? ROOT_KEYS.PRIVATE_ROOMS : ROOT_KEYS.RANDOM_ROOMS}/${roomId}/${GENERAL_ROOM_KEYS.GAME}`,
    currentRoundNumber: (roomId, isPrivateMatch = false) => `${DATABASE_PATHS_FOR_ROOMS.game(roomId, isPrivateMatch)}/${GENERAL_ROOM_KEYS.ROUND_NUMBER}`,
    gamePhase: (roomId, isPrivateMatch = false) => `${DATABASE_PATHS_FOR_ROOMS.game(roomId, isPrivateMatch)}/${GENERAL_ROOM_KEYS.PHASE}`,
    handSubmissionDeadline: (roomId, isPrivateMatch = false) => `${DATABASE_PATHS_FOR_ROOMS.game(roomId, isPrivateMatch)}/${GENERAL_ROOM_KEYS.HAND_SUBMISSION_DEADLINE}`,
    finalWinnerOfMatch: (roomId, isPrivateMatch = false) => `${DATABASE_PATHS_FOR_ROOMS.game(roomId, isPrivateMatch)}/${GENERAL_ROOM_KEYS.FINAL_WINNER_OF_MATCH}`,
    resolvedRound: (roomId, isPrivateMatch = false) => `${DATABASE_PATHS_FOR_ROOMS.game(roomId, isPrivateMatch)}/${GENERAL_ROOM_KEYS.RESOLVED_ROUND}`,
    resolvedHostHand: (roomId, isPrivateMatch = false) => `${DATABASE_PATHS_FOR_ROOMS.resolvedRound(roomId, isPrivateMatch)}/${GENERAL_ROOM_KEYS.HOST}/${GENERAL_ROOM_KEYS.SELECTED_HAND}`,
    resolvedGuestHand: (roomId, isPrivateMatch = false) => `${DATABASE_PATHS_FOR_ROOMS.resolvedRound(roomId, isPrivateMatch)}/${GENERAL_ROOM_KEYS.GUEST}/${GENERAL_ROOM_KEYS.SELECTED_HAND}`,
    nextPhaseAt: (roomId, isPrivateMatch = false) => `${DATABASE_PATHS_FOR_ROOMS.resolvedRound(roomId, isPrivateMatch)}/${GENERAL_ROOM_KEYS.NEXT_PHASE_AT}`,
    privateRoomJoinCode: (joinCodeHash) => `${ROOT_KEYS.PRIVATE_ROOM_JOIN_CODES}/${joinCodeHash}`,
    privateRoomJoinCodeRoomId: (joinCodeHash) => `${ROOT_KEYS.PRIVATE_ROOM_JOIN_CODES}/${joinCodeHash}/${PRIVATE_ROOM_JOIN_CODE_KEYS.ROOM_ID}`,
    privateRoomHiddenHand: (roomId, roundNumber) => `${ROOT_KEYS.PRIVATE_ROOM_HIDDEN_HAND}/${roomId}/${roundNumber}`,
};
