export declare const GENERAL_ROOM_KEYS: {
    readonly PUBLIC: "public";
    readonly CONFIDENTIAL: "confidential";
    readonly CREATED_AT: "createdAt";
    readonly RULES: "rules";
    readonly MATCH_POINT: "matchPoint";
    readonly THINKING_TIME_IN_SEC: "thinkingTimeInSec";
    readonly STATE: "state";
    readonly HOST: "host";
    readonly GUEST: "guest";
    readonly UID: "uid";
    readonly NAME: "name";
    readonly SCORE: "score";
    readonly MANA: "mana";
    readonly FINAL_WINNER_OF_MATCH: "finalWinnerOfMatch";
    readonly GAME: "game";
    readonly PHASE: "phase";
    readonly HAND_SUBMISSION_DEADLINE: "handSubmissionDeadline";
    readonly SUBMITTED_PLAYERS: "submittedPlayers";
    readonly ROUND_NUMBER: "roundNumber";
    readonly HANDS_OF: "handsOf";
    readonly RESOLVED_ROUND: "resolvedRound";
    readonly MANA_GAIN: "manaGain";
    readonly SCORE_GAIN: "scoreGain";
    readonly SELECTED_HAND: "selectedHand";
    readonly WINNER_OF_ROUND: "winnerOfRound";
    readonly RESOLVED_AT: "resolvedAt";
    readonly NEXT_PHASE_AT: "nextPhaseAt";
    readonly CHEATER: "cheater";
    readonly RESIGNER: "resigner";
    readonly CONNECTION_STATE: "connectionState";
    readonly RECONNECT_DEADLINE: "reconnectDeadline";
};
export declare const PRIVATE_ROOM_KEYS: {
    readonly SPECTATORS: "spectators";
    readonly JOIN_CODE_HASH: "joinCodeHash";
    readonly READY: "ready";
    readonly BACK_TO_LOBBY_AT: "backToLobbyAt";
    readonly GUEST_IS_KICKED_AT: "guestIsKickedAt";
};
export declare const PRIVATE_ROOM_JOIN_CODE_KEYS: {
    readonly ROOM_ID: "roomId";
    readonly CREATED_AT: "createdAt";
};
export declare const PRIVATE_ROOM_PRESENCE_KEYS: {
    readonly CONNECTED_AT: "connectedAt";
};
export declare const DATABASE_PATHS_FOR_ROOMS: {
    readonly privateRoomsRoot: () => "privateRooms";
    readonly privateRoomContainer: (roomId: string) => string;
    readonly privateRoom: (roomId: string) => string;
    readonly privateRoomState: (roomId: string) => string;
    readonly privateRoomGuestName: (roomId: string) => string;
    readonly guestScore: (roomId: string, isPrivateMatch?: boolean) => string;
    readonly guestMana: (roomId: string, isPrivateMatch?: boolean) => string;
    readonly hostScore: (roomId: string, isPrivateMatch?: boolean) => string;
    readonly hostMana: (roomId: string, isPrivateMatch?: boolean) => string;
    readonly privateRoomSpectator: (roomId: string) => string;
    readonly randomRoom: (roomId: string) => string;
    readonly game: (roomId: string, isPrivateMatch?: boolean) => string;
    readonly currentRoundNumber: (roomId: string, isPrivateMatch?: boolean) => string;
    readonly gamePhase: (roomId: string, isPrivateMatch?: boolean) => string;
    readonly handSubmissionDeadline: (roomId: string, isPrivateMatch?: boolean) => string;
    readonly finalWinnerOfMatch: (roomId: string, isPrivateMatch?: boolean) => string;
    readonly cheater: (roomId: string, isPrivateMatch?: boolean) => string;
    readonly resigner: (roomId: string, isPrivateMatch?: boolean) => string;
    readonly backToLobbyAt: (roomId: string) => string;
    readonly resolvedRound: (roomId: string, isPrivateMatch?: boolean) => string;
    readonly resolvedHostHand: (roomId: string, isPrivateMatch?: boolean) => string;
    readonly resolvedGuestHand: (roomId: string, isPrivateMatch?: boolean) => string;
    readonly nextPhaseAt: (roomId: string, isPrivateMatch?: boolean) => string;
    readonly guestIsKickedAt: (roomId: string) => string;
    readonly privateRoomHostConnectionState: (roomId: string) => string;
    readonly privateRoomGuestConnectionState: (roomId: string) => string;
    readonly privateRoomJoinCode: (joinCodeHash: string) => string;
    readonly privateRoomJoinCodeRoomId: (joinCodeHash: string) => string;
    readonly privateRoomConfidentialRoot: (roomId: string) => string;
    readonly privateRoomConfidential: (roomId: string, roundNumber: number) => string;
    readonly privateRoomPresenceRoot: (roomId: string) => string;
    readonly privateRoomPresenceOfUser: (roomId: string, uid: string) => string;
    readonly privateRoomConnection: (roomId: string, uid: string, connectionId: string) => string;
};
