export declare const GENERAL_ROOM_KEYS: {
    readonly CREATED_AT: "createdAt";
    readonly RULES: "rules";
    readonly MATCH_POINT: "matchPoint";
    readonly THINKING_TIME_IN_SEC: "thinkingTimeInSec";
    readonly STATE: "state";
    readonly HOST: "host";
    readonly GUEST: "guest";
    readonly UID: "uid";
    readonly NAME: "name";
    readonly SCORE: "score";
    readonly MANA: "mana";
    readonly HAS_FINISHED_INTERLUDE: "hasFinishedInterlude";
    readonly FINAL_WINNER_OF_MATCH: "finalWinnerOfMatch";
    readonly GAME: "game";
    readonly PHASE: "phase";
    readonly HAND_SUBMISSION_DEADLINE: "handSubmissionDeadline";
    readonly RECONNECT_DEADLINE: "reconnectDeadline";
    readonly SUBMITTED_PLAYERS: "submittedPlayers";
    readonly ROUND_NUMBER: "roundNumber";
    readonly HANDS_OF: "handsOf";
    readonly RESOLVED_ROUND: "resolvedRound";
    readonly MANA_GAIN: "manaGain";
    readonly SCORE_GAIN: "scoreGain";
    readonly SELECTED_HAND: "selectedHand";
    readonly WINNER_OF_ROUND: "winnerOfRound";
    readonly RESOLVED_AT: "resolvedAt";
    readonly NEXT_PHASE_AT: "nextPhaseAt";
};
export declare const PRIVATE_ROOM_KEYS: {
    readonly SPECTATORS: "spectators";
    readonly JOIN_CODE_HASH: "joinCodeHash";
    readonly READY: "ready";
};
export declare const PRIVATE_ROOM_JOIN_CODE_KEYS: {
    readonly ROOM_ID: "roomId";
    readonly CREATED_AT: "createdAt";
};
export declare const DATABASE_PATHS_FOR_ROOMS: {
    readonly privateRoomsRoot: () => "privateRooms";
    readonly privateRoom: (roomId: string) => string;
    readonly privateRoomState: (roomId: string) => string;
    readonly privateRoomGuestName: (roomId: string) => string;
    readonly guestScore: (roomId: string, isPrivateMatch?: boolean) => string;
    readonly guestMana: (roomId: string, isPrivateMatch?: boolean) => string;
    readonly hostScore: (roomId: string, isPrivateMatch?: boolean) => string;
    readonly hostMana: (roomId: string, isPrivateMatch?: boolean) => string;
    readonly privateRoomSpectator: (roomId: string) => string;
    readonly game: (roomId: string, isPrivateMatch?: boolean) => string;
    readonly currentRoundNumber: (roomId: string, isPrivateMatch?: boolean) => string;
    readonly gamePhase: (roomId: string, isPrivateMatch?: boolean) => string;
    readonly handSubmissionDeadline: (roomId: string, isPrivateMatch?: boolean) => string;
    readonly finalWinnerOfMatch: (roomId: string, isPrivateMatch?: boolean) => string;
    readonly resolvedRound: (roomId: string, isPrivateMatch?: boolean) => string;
    readonly nextPhaseAt: (roomId: string, isPrivateMatch?: boolean) => string;
    readonly privateRoomJoinCode: (joinCodeHash: string) => string;
    readonly privateRoomJoinCodeRoomId: (joinCodeHash: string) => string;
    readonly privateRoomHiddenHand: (roomId: string, roundNumber: number) => string;
};
