import { ROOT_KEYS } from "./root.js";
export const GENERAL_ROOM_KEYS = {
    PUBLIC: "public",
    CONFIDENTIAL: "confidential",
    CREATED_AT: "createdAt",
    RULES: "rules",
    MATCH_POINT: "matchPoint",
    THINKING_TIME_IN_SEC: "thinkingTimeInSec",
    STATE: "state",
    HOST: "host",
    GUEST: "guest",
    UID: "uid",
    NAME: "name",
    SCORE: "score",
    MANA: "mana",
    FINAL_WINNER_OF_MATCH: "finalWinnerOfMatch",
    GAME: "game",
    PHASE: "phase",
    HAND_SUBMISSION_DEADLINE: "handSubmissionDeadline",
    SUBMITTED_PLAYERS: "submittedPlayers",
    ROUND_NUMBER: "roundNumber",
    HANDS_OF: "handsOf",
    RESOLVED_ROUND: "resolvedRound",
    MANA_GAIN: "manaGain",
    SCORE_GAIN: "scoreGain",
    SELECTED_HAND: "selectedHand",
    WINNER_OF_ROUND: "winnerOfRound",
    RESOLVED_AT: "resolvedAt",
    NEXT_PHASE_AT: "nextPhaseAt",
    CHEATER: "cheater",
    RESIGNER: "resigner",
    CONNECTION_STATE: "connectionState",
    RECONNECT_DEADLINE: "reconnectDeadline",
};
export const PRIVATE_ROOM_KEYS = {
    SPECTATORS: "spectators",
    JOIN_CODE_HASH: "joinCodeHash",
    READY: "ready",
    BACK_TO_LOBBY_AT: "backToLobbyAt",
    GUEST_IS_KICKED_AT: "guestIsKickedAt",
};
export const PRIVATE_ROOM_JOIN_CODE_KEYS = {
    ROOM_ID: "roomId",
    CREATED_AT: "createdAt",
};
export const PRIVATE_ROOM_PRESENCE_KEYS = {
    CONNECTED_AT: "connectedAt",
};
export const DATABASE_PATHS_FOR_ROOMS = {
    privateRoomsRoot: () => ROOT_KEYS.PRIVATE_ROOMS,
    privateRoomContainer: (roomId) => `${ROOT_KEYS.PRIVATE_ROOMS}/${roomId}`,
    privateRoom: (roomId) => `${DATABASE_PATHS_FOR_ROOMS.privateRoomContainer(roomId)}/${GENERAL_ROOM_KEYS.PUBLIC}`,
    privateRoomState: (roomId) => `${DATABASE_PATHS_FOR_ROOMS.privateRoom(roomId)}/${GENERAL_ROOM_KEYS.STATE}`,
    privateRoomGuestName: (roomId) => `${DATABASE_PATHS_FOR_ROOMS.privateRoom(roomId)}/${GENERAL_ROOM_KEYS.GUEST}/${GENERAL_ROOM_KEYS.NAME}`,
    guestScore: (roomId, isPrivateMatch = false) => `${isPrivateMatch ? DATABASE_PATHS_FOR_ROOMS.privateRoom(roomId) : DATABASE_PATHS_FOR_ROOMS.randomRoom(roomId)}/${GENERAL_ROOM_KEYS.GUEST}/${GENERAL_ROOM_KEYS.SCORE}`,
    guestMana: (roomId, isPrivateMatch = false) => `${isPrivateMatch ? DATABASE_PATHS_FOR_ROOMS.privateRoom(roomId) : DATABASE_PATHS_FOR_ROOMS.randomRoom(roomId)}/${GENERAL_ROOM_KEYS.GUEST}/${GENERAL_ROOM_KEYS.MANA}`,
    hostScore: (roomId, isPrivateMatch = false) => `${isPrivateMatch ? DATABASE_PATHS_FOR_ROOMS.privateRoom(roomId) : DATABASE_PATHS_FOR_ROOMS.randomRoom(roomId)}/${GENERAL_ROOM_KEYS.HOST}/${GENERAL_ROOM_KEYS.SCORE}`,
    hostMana: (roomId, isPrivateMatch = false) => `${isPrivateMatch ? DATABASE_PATHS_FOR_ROOMS.privateRoom(roomId) : DATABASE_PATHS_FOR_ROOMS.randomRoom(roomId)}/${GENERAL_ROOM_KEYS.HOST}/${GENERAL_ROOM_KEYS.MANA}`,
    privateRoomSpectator: (roomId) => `${DATABASE_PATHS_FOR_ROOMS.privateRoom(roomId)}/${PRIVATE_ROOM_KEYS.SPECTATORS}`,
    randomRoom: (roomId) => `${ROOT_KEYS.RANDOM_ROOMS}/${roomId}/${GENERAL_ROOM_KEYS.PUBLIC}`,
    game: (roomId, isPrivateMatch = false) => `${isPrivateMatch ? DATABASE_PATHS_FOR_ROOMS.privateRoom(roomId) : DATABASE_PATHS_FOR_ROOMS.randomRoom(roomId)}/${GENERAL_ROOM_KEYS.GAME}`,
    currentRoundNumber: (roomId, isPrivateMatch = false) => `${DATABASE_PATHS_FOR_ROOMS.game(roomId, isPrivateMatch)}/${GENERAL_ROOM_KEYS.ROUND_NUMBER}`,
    gamePhase: (roomId, isPrivateMatch = false) => `${DATABASE_PATHS_FOR_ROOMS.game(roomId, isPrivateMatch)}/${GENERAL_ROOM_KEYS.PHASE}`,
    handSubmissionDeadline: (roomId, isPrivateMatch = false) => `${DATABASE_PATHS_FOR_ROOMS.game(roomId, isPrivateMatch)}/${GENERAL_ROOM_KEYS.HAND_SUBMISSION_DEADLINE}`,
    finalWinnerOfMatch: (roomId, isPrivateMatch = false) => `${DATABASE_PATHS_FOR_ROOMS.game(roomId, isPrivateMatch)}/${GENERAL_ROOM_KEYS.FINAL_WINNER_OF_MATCH}`,
    cheater: (roomId, isPrivateMatch = false) => `${DATABASE_PATHS_FOR_ROOMS.game(roomId, isPrivateMatch)}/${GENERAL_ROOM_KEYS.CHEATER}`,
    resigner: (roomId, isPrivateMatch = false) => `${DATABASE_PATHS_FOR_ROOMS.game(roomId, isPrivateMatch)}/${GENERAL_ROOM_KEYS.RESIGNER}`,
    backToLobbyAt: (roomId) => `${DATABASE_PATHS_FOR_ROOMS.game(roomId, true)}/${PRIVATE_ROOM_KEYS.BACK_TO_LOBBY_AT}`,
    resolvedRound: (roomId, isPrivateMatch = false) => `${DATABASE_PATHS_FOR_ROOMS.game(roomId, isPrivateMatch)}/${GENERAL_ROOM_KEYS.RESOLVED_ROUND}`,
    resolvedHostHand: (roomId, isPrivateMatch = false) => `${DATABASE_PATHS_FOR_ROOMS.resolvedRound(roomId, isPrivateMatch)}/${GENERAL_ROOM_KEYS.HOST}/${GENERAL_ROOM_KEYS.SELECTED_HAND}`,
    resolvedGuestHand: (roomId, isPrivateMatch = false) => `${DATABASE_PATHS_FOR_ROOMS.resolvedRound(roomId, isPrivateMatch)}/${GENERAL_ROOM_KEYS.GUEST}/${GENERAL_ROOM_KEYS.SELECTED_HAND}`,
    nextPhaseAt: (roomId, isPrivateMatch = false) => `${DATABASE_PATHS_FOR_ROOMS.resolvedRound(roomId, isPrivateMatch)}/${GENERAL_ROOM_KEYS.NEXT_PHASE_AT}`,
    guestIsKickedAt: (roomId) => `${DATABASE_PATHS_FOR_ROOMS.privateRoom(roomId)}/${PRIVATE_ROOM_KEYS.GUEST_IS_KICKED_AT}`,
    privateRoomHostConnectionState: (roomId) => `${DATABASE_PATHS_FOR_ROOMS.privateRoom(roomId)}` +
        `/${GENERAL_ROOM_KEYS.HOST}` +
        `/${GENERAL_ROOM_KEYS.CONNECTION_STATE}`,
    privateRoomGuestConnectionState: (roomId) => `${DATABASE_PATHS_FOR_ROOMS.privateRoom(roomId)}` +
        `/${GENERAL_ROOM_KEYS.GUEST}` +
        `/${GENERAL_ROOM_KEYS.CONNECTION_STATE}`,
    privateRoomJoinCode: (joinCodeHash) => `${ROOT_KEYS.PRIVATE_ROOM_JOIN_CODES}/${joinCodeHash}`,
    privateRoomJoinCodeRoomId: (joinCodeHash) => `${ROOT_KEYS.PRIVATE_ROOM_JOIN_CODES}/${joinCodeHash}/${PRIVATE_ROOM_JOIN_CODE_KEYS.ROOM_ID}`,
    privateRoomConfidentialRoot: (roomId) => `${DATABASE_PATHS_FOR_ROOMS.privateRoomContainer(roomId)}/${GENERAL_ROOM_KEYS.CONFIDENTIAL}`,
    privateRoomConfidential: (roomId, roundNumber) => `${DATABASE_PATHS_FOR_ROOMS.privateRoomConfidentialRoot(roomId)}/${roundNumber}`,
    privateRoomPresenceRoot: (roomId) => `${ROOT_KEYS.PRIVATE_ROOM_PRESENCE}/${roomId}`,
    privateRoomPresenceOfUser: (roomId, uid) => `${DATABASE_PATHS_FOR_ROOMS.privateRoomPresenceRoot(roomId)}/${uid}`,
    privateRoomConnection: (roomId, uid, connectionId) => `${DATABASE_PATHS_FOR_ROOMS.privateRoomPresenceOfUser(roomId, uid)}/${connectionId}`,
};
